import { z } from 'zod';
export declare const bannerSchema: z.ZodObject<{
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    text_uz: z.ZodOptional<z.ZodString>;
    text_ru: z.ZodOptional<z.ZodString>;
    ctaText_uz: z.ZodOptional<z.ZodString>;
    ctaText_ru: z.ZodOptional<z.ZodString>;
    ctaLink: z.ZodNullable<z.ZodUnion<[z.ZodEffects<z.ZodOptional<z.ZodString>, string, string>, z.ZodOptional<z.ZodLiteral<"">>]>>;
    imageId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    text_uz?: string;
    text_ru?: string;
    ctaText_uz?: string;
    ctaText_ru?: string;
    status?: "published" | "draft" | "archived";
    ctaLink?: string;
    imageId?: string;
    order?: number;
}, {
    title_uz?: string;
    title_ru?: string;
    text_uz?: string;
    text_ru?: string;
    ctaText_uz?: string;
    ctaText_ru?: string;
    status?: "published" | "draft" | "archived";
    ctaLink?: string;
    imageId?: string;
    order?: number;
}>;
export declare const serviceSchema: z.ZodObject<{
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    excerpt_uz: z.ZodOptional<z.ZodString>;
    excerpt_ru: z.ZodOptional<z.ZodString>;
    body_uz: z.ZodOptional<z.ZodString>;
    body_ru: z.ZodOptional<z.ZodString>;
    slug: z.ZodString;
    coverId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    excerpt_uz?: string;
    excerpt_ru?: string;
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    coverId?: string;
}, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    excerpt_uz?: string;
    excerpt_ru?: string;
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    coverId?: string;
}>;
export declare const brandSchema: z.ZodObject<{
    name: z.ZodString;
    slug: z.ZodString;
    logoId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    desc_uz: z.ZodOptional<z.ZodString>;
    desc_ru: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    slug?: string;
    name?: string;
    logoId?: string;
    desc_uz?: string;
    desc_ru?: string;
}, {
    slug?: string;
    name?: string;
    logoId?: string;
    desc_uz?: string;
    desc_ru?: string;
}>;
export declare const productCategorySchema: z.ZodObject<{
    name_uz: z.ZodString;
    name_ru: z.ZodString;
    slug: z.ZodString;
    description_uz: z.ZodOptional<z.ZodString>;
    description_ru: z.ZodOptional<z.ZodString>;
    icon: z.ZodOptional<z.ZodString>;
    imageId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    parentId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    imageId?: string;
    order?: number;
    slug?: string;
    name_uz?: string;
    name_ru?: string;
    description_uz?: string;
    description_ru?: string;
    icon?: string;
    parentId?: string;
}, {
    imageId?: string;
    order?: number;
    slug?: string;
    name_uz?: string;
    name_ru?: string;
    description_uz?: string;
    description_ru?: string;
    icon?: string;
    parentId?: string;
}>;
export declare const productSchema: z.ZodObject<{
    name_uz: z.ZodString;
    name_ru: z.ZodString;
    slug: z.ZodString;
    description_uz: z.ZodOptional<z.ZodString>;
    description_ru: z.ZodOptional<z.ZodString>;
    price: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    stock: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    brandId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    categoryId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    specsText: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    galleryIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    audience: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    formFactors: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    signalProcessing: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    powerLevel: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    hearingLossLevels: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    smartphoneCompatibility: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    tinnitusSupport: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    paymentOptions: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    availabilityStatus: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    intro_uz: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    intro_ru: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    features_uz: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    features_ru: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    benefits_uz: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    benefits_ru: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    tech_uz: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    tech_ru: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fittingRange_uz: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fittingRange_ru: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    regulatoryNote_uz: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    regulatoryNote_ru: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    galleryUrls: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    relatedProductIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    usefulArticleSlugs: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    status?: "published" | "draft" | "archived";
    slug?: string;
    name_uz?: string;
    name_ru?: string;
    description_uz?: string;
    description_ru?: string;
    price?: number;
    stock?: number;
    brandId?: string;
    categoryId?: string;
    specsText?: string;
    galleryIds?: string[];
    audience?: string[];
    formFactors?: string[];
    signalProcessing?: string;
    powerLevel?: string;
    hearingLossLevels?: string[];
    smartphoneCompatibility?: string[];
    tinnitusSupport?: boolean;
    paymentOptions?: string[];
    availabilityStatus?: string;
    intro_uz?: string;
    intro_ru?: string;
    features_uz?: string[];
    features_ru?: string[];
    benefits_uz?: string[];
    benefits_ru?: string[];
    tech_uz?: string;
    tech_ru?: string;
    fittingRange_uz?: string;
    fittingRange_ru?: string;
    regulatoryNote_uz?: string;
    regulatoryNote_ru?: string;
    galleryUrls?: string[];
    relatedProductIds?: string[];
    usefulArticleSlugs?: string[];
}, {
    status?: "published" | "draft" | "archived";
    slug?: string;
    name_uz?: string;
    name_ru?: string;
    description_uz?: string;
    description_ru?: string;
    price?: number;
    stock?: number;
    brandId?: string;
    categoryId?: string;
    specsText?: string;
    galleryIds?: string[];
    audience?: string[];
    formFactors?: string[];
    signalProcessing?: string;
    powerLevel?: string;
    hearingLossLevels?: string[];
    smartphoneCompatibility?: string[];
    tinnitusSupport?: boolean;
    paymentOptions?: string[];
    availabilityStatus?: string;
    intro_uz?: string;
    intro_ru?: string;
    features_uz?: string[];
    features_ru?: string[];
    benefits_uz?: string[];
    benefits_ru?: string[];
    tech_uz?: string;
    tech_ru?: string;
    fittingRange_uz?: string;
    fittingRange_ru?: string;
    regulatoryNote_uz?: string;
    regulatoryNote_ru?: string;
    galleryUrls?: string[];
    relatedProductIds?: string[];
    usefulArticleSlugs?: string[];
}>;
export declare const postSchema: z.ZodObject<{
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    body_uz: z.ZodString;
    body_ru: z.ZodString;
    slug: z.ZodString;
    excerpt_uz: z.ZodOptional<z.ZodString>;
    excerpt_ru: z.ZodOptional<z.ZodString>;
    coverId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
    publishAt: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    excerpt_uz?: string;
    excerpt_ru?: string;
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    coverId?: string;
    tags?: string[];
    publishAt?: Date;
}, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    excerpt_uz?: string;
    excerpt_ru?: string;
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    coverId?: string;
    tags?: string[];
    publishAt?: Date;
}>;
export declare const faqSchema: z.ZodObject<{
    question_uz: z.ZodString;
    question_ru: z.ZodString;
    answer_uz: z.ZodString;
    answer_ru: z.ZodString;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    status?: "published" | "draft" | "archived";
    order?: number;
    question_uz?: string;
    question_ru?: string;
    answer_uz?: string;
    answer_ru?: string;
}, {
    status?: "published" | "draft" | "archived";
    order?: number;
    question_uz?: string;
    question_ru?: string;
    answer_uz?: string;
    answer_ru?: string;
}>;
export declare const branchSchema: z.ZodObject<{
    name_uz: z.ZodString;
    name_ru: z.ZodString;
    address_uz: z.ZodString;
    address_ru: z.ZodString;
    phone: z.ZodString;
    phones: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    imageId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    map_iframe: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    imageId?: string;
    order?: number;
    name_uz?: string;
    name_ru?: string;
    address_uz?: string;
    address_ru?: string;
    phone?: string;
    phones?: string[];
    map_iframe?: string;
}, {
    imageId?: string;
    order?: number;
    name_uz?: string;
    name_ru?: string;
    address_uz?: string;
    address_ru?: string;
    phone?: string;
    phones?: string[];
    map_iframe?: string;
}>;
export declare const leadSchema: z.ZodObject<{
    name: z.ZodString;
    phone: z.ZodString;
    email: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    source: z.ZodOptional<z.ZodString>;
    message: z.ZodOptional<z.ZodString>;
    productId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    message?: string;
    name?: string;
    phone?: string;
    email?: string;
    source?: string;
    productId?: string;
}, {
    message?: string;
    name?: string;
    phone?: string;
    email?: string;
    source?: string;
    productId?: string;
}>;
export declare const pageSchema: z.ZodObject<{
    slug: z.ZodString;
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    body_uz: z.ZodOptional<z.ZodString>;
    body_ru: z.ZodOptional<z.ZodString>;
    metaTitle_uz: z.ZodOptional<z.ZodString>;
    metaTitle_ru: z.ZodOptional<z.ZodString>;
    metaDescription_uz: z.ZodOptional<z.ZodString>;
    metaDescription_ru: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    metaTitle_uz?: string;
    metaTitle_ru?: string;
    metaDescription_uz?: string;
    metaDescription_ru?: string;
}, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    body_uz?: string;
    body_ru?: string;
    slug?: string;
    metaTitle_uz?: string;
    metaTitle_ru?: string;
    metaDescription_uz?: string;
    metaDescription_ru?: string;
}>;
export declare const homepageHearingAidSchema: z.ZodObject<{
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    description_uz: z.ZodOptional<z.ZodString>;
    description_ru: z.ZodOptional<z.ZodString>;
    link: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    imageId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    link?: string;
    status?: "published" | "draft" | "archived";
    imageId?: string;
    order?: number;
    description_uz?: string;
    description_ru?: string;
}, {
    title_uz?: string;
    title_ru?: string;
    link?: string;
    status?: "published" | "draft" | "archived";
    imageId?: string;
    order?: number;
    description_uz?: string;
    description_ru?: string;
}>;
export declare const homepageJourneyStepSchema: z.ZodObject<{
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    description_uz: z.ZodOptional<z.ZodString>;
    description_ru: z.ZodOptional<z.ZodString>;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    description_uz?: string;
    description_ru?: string;
}, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    description_uz?: string;
    description_ru?: string;
}>;
export declare const homepageNewsItemSchema: z.ZodObject<{
    postId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    title_uz: z.ZodString;
    title_ru: z.ZodString;
    excerpt_uz: z.ZodOptional<z.ZodString>;
    excerpt_ru: z.ZodOptional<z.ZodString>;
    slug: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    publishedAt: z.ZodNullable<z.ZodOptional<z.ZodDate>>;
    order: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["published", "draft", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    excerpt_uz?: string;
    excerpt_ru?: string;
    slug?: string;
    postId?: string;
    publishedAt?: Date;
}, {
    title_uz?: string;
    title_ru?: string;
    status?: "published" | "draft" | "archived";
    order?: number;
    excerpt_uz?: string;
    excerpt_ru?: string;
    slug?: string;
    postId?: string;
    publishedAt?: Date;
}>;
//# sourceMappingURL=content.d.ts.map