#!/bin/bash

# Manual deployment script with step-by-step instructions
# Run each command manually and enter password when prompted

SERVER_USER="user1"
SERVER_IP="192.168.20.66"
SERVER_PATH="/var/www/acousticuz"
LOCAL_STANDALONE="apps/frontend/.next/standalone/apps/frontend"
LOCAL_PUBLIC="apps/frontend/public"

echo "🚀 Manual Deployment Guide"
echo "=========================="
echo ""
echo "📦 Server: ${SERVER_USER}@${SERVER_IP}"
echo "📁 Target: ${SERVER_PATH}"
echo ""
echo "Follow these steps one by one:"
echo ""

echo "📋 Step 1: Create directory structure on server"
echo "Run this command:"
echo "  ssh ${SERVER_USER}@${SERVER_IP} 'sudo mkdir -p ${SERVER_PATH}/apps/frontend && sudo chown -R ${SERVER_USER}:${SERVER_USER} ${SERVER_PATH}'"
echo ""
read -p "Press Enter after completing Step 1..."

echo ""
echo "📋 Step 2: Copy application files (excluding node_modules)"
echo "Run this command:"
echo "  rsync -avz --progress --exclude 'node_modules' --exclude '.next/cache' ${LOCAL_STANDALONE}/ ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}/apps/frontend/"
echo ""
read -p "Press Enter after completing Step 2..."

echo ""
echo "📋 Step 3: Copy public folder"
echo "Run this command:"
echo "  rsync -avz --progress ${LOCAL_PUBLIC}/ ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}/apps/frontend/public/"
echo ""
read -p "Press Enter after completing Step 3..."

echo ""
echo "📋 Step 4: Copy .next static files"
echo "Run this command:"
echo "  rsync -avz --progress --include '.next/static/**' --include '.next/server/**' --exclude '.next/cache/**' apps/frontend/.next/ ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}/apps/frontend/.next/"
echo ""
read -p "Press Enter after completing Step 4..."

echo ""
echo "📋 Step 5: Install dependencies on server"
echo "Run this command:"
echo "  ssh ${SERVER_USER}@${SERVER_IP} 'cd ${SERVER_PATH}/apps/frontend && npm install --production'"
echo ""
read -p "Press Enter after completing Step 5..."

echo ""
echo "📋 Step 6: Create .env.production file"
echo "Run this command:"
echo "  ssh ${SERVER_USER}@${SERVER_IP} 'cd ${SERVER_PATH}/apps/frontend && cat > .env.production << EOF"
echo "NODE_ENV=production"
echo "PORT=3000"
echo "NEXT_PUBLIC_API_URL=http://localhost:3001/api"
echo "NEXT_PUBLIC_SITE_URL=https://acoustic.uz"
echo "EOF'"
echo ""
read -p "Press Enter after completing Step 6..."

echo ""
echo "✅ Deployment completed!"
echo ""
echo "📝 Next steps:"
echo "   1. SSH to server: ssh ${SERVER_USER}@${SERVER_IP}"
echo "   2. Go to: cd ${SERVER_PATH}/apps/frontend"
echo "   3. Update .env.production with correct values"
echo "   4. Start: node server.js"
echo ""

