import { HearingTestService } from './hearing-test.service';
export declare class HearingTestController {
    private readonly hearingTestService;
    constructor(hearingTestService: HearingTestService);
    create(createDto: unknown): Promise<{
        name: string | null;
        source: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        email: string | null;
        phone: string | null;
        deviceType: string;
        volumeLevel: number | null;
        leftEarResults: import("@prisma/client/runtime/library").JsonValue;
        rightEarResults: import("@prisma/client/runtime/library").JsonValue;
        leftEarScore: number | null;
        rightEarScore: number | null;
        overallScore: number | null;
        leftEarLevel: string | null;
        rightEarLevel: string | null;
        notes: string | null;
    }>;
    findAll(): Promise<{
        name: string | null;
        source: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        email: string | null;
        phone: string | null;
        deviceType: string;
        volumeLevel: number | null;
        leftEarResults: import("@prisma/client/runtime/library").JsonValue;
        rightEarResults: import("@prisma/client/runtime/library").JsonValue;
        leftEarScore: number | null;
        rightEarScore: number | null;
        overallScore: number | null;
        leftEarLevel: string | null;
        rightEarLevel: string | null;
        notes: string | null;
    }[]>;
    findOne(id: string): Promise<{
        name: string | null;
        source: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        email: string | null;
        phone: string | null;
        deviceType: string;
        volumeLevel: number | null;
        leftEarResults: import("@prisma/client/runtime/library").JsonValue;
        rightEarResults: import("@prisma/client/runtime/library").JsonValue;
        leftEarScore: number | null;
        rightEarScore: number | null;
        overallScore: number | null;
        leftEarLevel: string | null;
        rightEarLevel: string | null;
        notes: string | null;
    } | null>;
    update(id: string, updateDto: {
        status?: string;
        notes?: string;
    }): Promise<{
        name: string | null;
        source: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        email: string | null;
        phone: string | null;
        deviceType: string;
        volumeLevel: number | null;
        leftEarResults: import("@prisma/client/runtime/library").JsonValue;
        rightEarResults: import("@prisma/client/runtime/library").JsonValue;
        leftEarScore: number | null;
        rightEarScore: number | null;
        overallScore: number | null;
        leftEarLevel: string | null;
        rightEarLevel: string | null;
        notes: string | null;
    }>;
    remove(id: string): Promise<{
        name: string | null;
        source: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        email: string | null;
        phone: string | null;
        deviceType: string;
        volumeLevel: number | null;
        leftEarResults: import("@prisma/client/runtime/library").JsonValue;
        rightEarResults: import("@prisma/client/runtime/library").JsonValue;
        leftEarScore: number | null;
        rightEarScore: number | null;
        overallScore: number | null;
        leftEarLevel: string | null;
        rightEarLevel: string | null;
        notes: string | null;
    }>;
}
//# sourceMappingURL=hearing-test.controller.d.ts.map