import { ServiceCategoriesService } from './service-categories.service';
export declare class ServiceCategoriesController {
    private readonly service;
    constructor(service: ServiceCategoriesService);
    findAll(publicOnly?: string, limit?: string, offset?: string): Promise<({
        [x: string]: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[] | ({
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        })[] | ({
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        } | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        })[] | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    })[] | {
        items: ({
            [x: string]: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            }[] | ({
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            } | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            })[] | ({
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            } | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            })[] | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            }[];
            [x: number]: never;
            [x: symbol]: never;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findBySlug(slug: string, publicOnly?: string): Promise<({
        image: {
            id: string;
            size: number | null;
            createdAt: Date;
            updatedAt: Date;
            alt_uz: string | null;
            alt_ru: string | null;
            url: string;
            filename: string | null;
            mimeType: string | null;
        } | null;
        children: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[];
        services: ({
            cover: {
                id: string;
                size: number | null;
                createdAt: Date;
                updatedAt: Date;
                alt_uz: string | null;
                alt_ru: string | null;
                url: string;
                filename: string | null;
                mimeType: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        })[];
        parent: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    }) | null>;
    findAllAdmin(): Promise<({
        [x: string]: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[] | ({
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        })[] | ({
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        } | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        })[] | {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    })[] | {
        items: ({
            [x: string]: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            }[] | ({
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            } | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            })[] | ({
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            } | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            })[] | {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                title_uz: string;
                title_ru: string;
                body_uz: string | null;
                body_ru: string | null;
                slug: string;
                categoryId: string | null;
                excerpt_uz: string | null;
                excerpt_ru: string | null;
                coverId: string | null;
                status: string;
                order: number;
            }[];
            [x: number]: never;
            [x: symbol]: never;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findOne(id: string): Promise<({
        image: {
            id: string;
            size: number | null;
            createdAt: Date;
            updatedAt: Date;
            alt_uz: string | null;
            alt_ru: string | null;
            url: string;
            filename: string | null;
            mimeType: string | null;
        } | null;
        children: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[];
        services: ({
            cover: {
                id: string;
                size: number | null;
                createdAt: Date;
                updatedAt: Date;
                alt_uz: string | null;
                alt_ru: string | null;
                url: string;
                filename: string | null;
                mimeType: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        })[];
        parent: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    }) | null>;
    create(dto: unknown): Promise<{
        image: {
            id: string;
            size: number | null;
            createdAt: Date;
            updatedAt: Date;
            alt_uz: string | null;
            alt_ru: string | null;
            url: string;
            filename: string | null;
            mimeType: string | null;
        } | null;
        children: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[];
        services: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        }[];
        parent: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    }>;
    update(id: string, dto: unknown): Promise<{
        image: {
            id: string;
            size: number | null;
            createdAt: Date;
            updatedAt: Date;
            alt_uz: string | null;
            alt_ru: string | null;
            url: string;
            filename: string | null;
            mimeType: string | null;
        } | null;
        children: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        }[];
        services: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            title_uz: string;
            title_ru: string;
            body_uz: string | null;
            body_ru: string | null;
            slug: string;
            categoryId: string | null;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
            coverId: string | null;
            status: string;
            order: number;
        }[];
        parent: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    }>;
    remove(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        imageId: string | null;
        order: number;
        icon: string | null;
        parentId: string | null;
    }>;
}
//# sourceMappingURL=service-categories.controller.d.ts.map