"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateProductDto = void 0;
const swagger_1 = require("@nestjs/swagger");
const class_validator_1 = require("class-validator");
let CreateProductDto = (() => {
    let _name_uz_decorators;
    let _name_uz_initializers = [];
    let _name_uz_extraInitializers = [];
    let _name_ru_decorators;
    let _name_ru_initializers = [];
    let _name_ru_extraInitializers = [];
    let _slug_decorators;
    let _slug_initializers = [];
    let _slug_extraInitializers = [];
    let _productType_decorators;
    let _productType_initializers = [];
    let _productType_extraInitializers = [];
    let _description_uz_decorators;
    let _description_uz_initializers = [];
    let _description_uz_extraInitializers = [];
    let _description_ru_decorators;
    let _description_ru_initializers = [];
    let _description_ru_extraInitializers = [];
    let _price_decorators;
    let _price_initializers = [];
    let _price_extraInitializers = [];
    let _stock_decorators;
    let _stock_initializers = [];
    let _stock_extraInitializers = [];
    let _brandId_decorators;
    let _brandId_initializers = [];
    let _brandId_extraInitializers = [];
    let _categoryId_decorators;
    let _categoryId_initializers = [];
    let _categoryId_extraInitializers = [];
    let _catalogIds_decorators;
    let _catalogIds_initializers = [];
    let _catalogIds_extraInitializers = [];
    let _galleryIds_decorators;
    let _galleryIds_initializers = [];
    let _galleryIds_extraInitializers = [];
    let _galleryUrls_decorators;
    let _galleryUrls_initializers = [];
    let _galleryUrls_extraInitializers = [];
    let _specsText_decorators;
    let _specsText_initializers = [];
    let _specsText_extraInitializers = [];
    let _audience_decorators;
    let _audience_initializers = [];
    let _audience_extraInitializers = [];
    let _formFactors_decorators;
    let _formFactors_initializers = [];
    let _formFactors_extraInitializers = [];
    let _signalProcessing_decorators;
    let _signalProcessing_initializers = [];
    let _signalProcessing_extraInitializers = [];
    let _powerLevel_decorators;
    let _powerLevel_initializers = [];
    let _powerLevel_extraInitializers = [];
    let _hearingLossLevels_decorators;
    let _hearingLossLevels_initializers = [];
    let _hearingLossLevels_extraInitializers = [];
    let _smartphoneCompatibility_decorators;
    let _smartphoneCompatibility_initializers = [];
    let _smartphoneCompatibility_extraInitializers = [];
    let _tinnitusSupport_decorators;
    let _tinnitusSupport_initializers = [];
    let _tinnitusSupport_extraInitializers = [];
    let _paymentOptions_decorators;
    let _paymentOptions_initializers = [];
    let _paymentOptions_extraInitializers = [];
    let _availabilityStatus_decorators;
    let _availabilityStatus_initializers = [];
    let _availabilityStatus_extraInitializers = [];
    let _intro_uz_decorators;
    let _intro_uz_initializers = [];
    let _intro_uz_extraInitializers = [];
    let _intro_ru_decorators;
    let _intro_ru_initializers = [];
    let _intro_ru_extraInitializers = [];
    let _features_uz_decorators;
    let _features_uz_initializers = [];
    let _features_uz_extraInitializers = [];
    let _features_ru_decorators;
    let _features_ru_initializers = [];
    let _features_ru_extraInitializers = [];
    let _benefits_uz_decorators;
    let _benefits_uz_initializers = [];
    let _benefits_uz_extraInitializers = [];
    let _benefits_ru_decorators;
    let _benefits_ru_initializers = [];
    let _benefits_ru_extraInitializers = [];
    let _tech_uz_decorators;
    let _tech_uz_initializers = [];
    let _tech_uz_extraInitializers = [];
    let _tech_ru_decorators;
    let _tech_ru_initializers = [];
    let _tech_ru_extraInitializers = [];
    let _fittingRange_uz_decorators;
    let _fittingRange_uz_initializers = [];
    let _fittingRange_uz_extraInitializers = [];
    let _fittingRange_ru_decorators;
    let _fittingRange_ru_initializers = [];
    let _fittingRange_ru_extraInitializers = [];
    let _regulatoryNote_uz_decorators;
    let _regulatoryNote_uz_initializers = [];
    let _regulatoryNote_uz_extraInitializers = [];
    let _regulatoryNote_ru_decorators;
    let _regulatoryNote_ru_initializers = [];
    let _regulatoryNote_ru_extraInitializers = [];
    let _relatedProductIds_decorators;
    let _relatedProductIds_initializers = [];
    let _relatedProductIds_extraInitializers = [];
    let _usefulArticleSlugs_decorators;
    let _usefulArticleSlugs_initializers = [];
    let _usefulArticleSlugs_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    return class CreateProductDto {
        static {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _name_uz_decorators = [(0, swagger_1.ApiProperty)({ description: 'Mahsulot nomi (o\'zbekcha)' }), (0, class_validator_1.IsString)()];
            _name_ru_decorators = [(0, swagger_1.ApiProperty)({ description: 'Mahsulot nomi (ruscha)' }), (0, class_validator_1.IsString)()];
            _slug_decorators = [(0, swagger_1.ApiProperty)({ description: 'Mahsulot slug' }), (0, class_validator_1.IsString)()];
            _productType_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Mahsulot turi' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(['hearing-aids', 'accessories', 'interacoustics'])];
            _description_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Tavsif (o\'zbekcha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _description_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Tavsif (ruscha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _price_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Narx' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsNumber)(), (0, class_validator_1.IsPositive)()];
            _stock_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Ombor miqdori' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsNumber)(), (0, class_validator_1.Min)(0)];
            _brandId_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Brend ID' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _categoryId_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Kategoriya ID' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _catalogIds_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Katalog ID lar', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _galleryIds_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Rasm ID lar', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _galleryUrls_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Rasm URL lar', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _specsText_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Xususiyatlar matni' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _audience_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Auditoriya', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _formFactors_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Korpus turlari', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _signalProcessing_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Signal qayta ishlash' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _powerLevel_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Quvvat darajasi' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _hearingLossLevels_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Eshitish yo\'qotish darajalari', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _smartphoneCompatibility_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Smartfon mosligi', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _tinnitusSupport_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Tinnitus qo\'llab-quvvatlash' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsBoolean)()];
            _paymentOptions_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'To\'lov usullari', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _availabilityStatus_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Mavjudlik holati' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _intro_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Kirish matni (o\'zbekcha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _intro_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Kirish matni (ruscha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _features_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Xususiyatlar (o\'zbekcha)', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _features_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Xususiyatlar (ruscha)', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _benefits_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Afzalliklar (o\'zbekcha)', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _benefits_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Afzalliklar (ruscha)', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _tech_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Texnologiyalar (o\'zbekcha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _tech_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Texnologiyalar (ruscha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _fittingRange_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Sozlash diapazoni (o\'zbekcha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _fittingRange_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Sozlash diapazoni (ruscha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _regulatoryNote_uz_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Regulyator eslatma (o\'zbekcha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _regulatoryNote_ru_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Regulyator eslatma (ruscha)' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsString)()];
            _relatedProductIds_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Bog\'liq mahsulot ID lar', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _usefulArticleSlugs_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Foydali maqola slug lar', type: [String] }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsArray)(), (0, class_validator_1.IsString)({ each: true })];
            _status_decorators = [(0, swagger_1.ApiPropertyOptional)({ description: 'Holat', enum: ['published', 'draft', 'archived'], default: 'published' }), (0, class_validator_1.IsOptional)(), (0, class_validator_1.IsEnum)(['published', 'draft', 'archived'])];
            __esDecorate(null, null, _name_uz_decorators, { kind: "field", name: "name_uz", static: false, private: false, access: { has: obj => "name_uz" in obj, get: obj => obj.name_uz, set: (obj, value) => { obj.name_uz = value; } }, metadata: _metadata }, _name_uz_initializers, _name_uz_extraInitializers);
            __esDecorate(null, null, _name_ru_decorators, { kind: "field", name: "name_ru", static: false, private: false, access: { has: obj => "name_ru" in obj, get: obj => obj.name_ru, set: (obj, value) => { obj.name_ru = value; } }, metadata: _metadata }, _name_ru_initializers, _name_ru_extraInitializers);
            __esDecorate(null, null, _slug_decorators, { kind: "field", name: "slug", static: false, private: false, access: { has: obj => "slug" in obj, get: obj => obj.slug, set: (obj, value) => { obj.slug = value; } }, metadata: _metadata }, _slug_initializers, _slug_extraInitializers);
            __esDecorate(null, null, _productType_decorators, { kind: "field", name: "productType", static: false, private: false, access: { has: obj => "productType" in obj, get: obj => obj.productType, set: (obj, value) => { obj.productType = value; } }, metadata: _metadata }, _productType_initializers, _productType_extraInitializers);
            __esDecorate(null, null, _description_uz_decorators, { kind: "field", name: "description_uz", static: false, private: false, access: { has: obj => "description_uz" in obj, get: obj => obj.description_uz, set: (obj, value) => { obj.description_uz = value; } }, metadata: _metadata }, _description_uz_initializers, _description_uz_extraInitializers);
            __esDecorate(null, null, _description_ru_decorators, { kind: "field", name: "description_ru", static: false, private: false, access: { has: obj => "description_ru" in obj, get: obj => obj.description_ru, set: (obj, value) => { obj.description_ru = value; } }, metadata: _metadata }, _description_ru_initializers, _description_ru_extraInitializers);
            __esDecorate(null, null, _price_decorators, { kind: "field", name: "price", static: false, private: false, access: { has: obj => "price" in obj, get: obj => obj.price, set: (obj, value) => { obj.price = value; } }, metadata: _metadata }, _price_initializers, _price_extraInitializers);
            __esDecorate(null, null, _stock_decorators, { kind: "field", name: "stock", static: false, private: false, access: { has: obj => "stock" in obj, get: obj => obj.stock, set: (obj, value) => { obj.stock = value; } }, metadata: _metadata }, _stock_initializers, _stock_extraInitializers);
            __esDecorate(null, null, _brandId_decorators, { kind: "field", name: "brandId", static: false, private: false, access: { has: obj => "brandId" in obj, get: obj => obj.brandId, set: (obj, value) => { obj.brandId = value; } }, metadata: _metadata }, _brandId_initializers, _brandId_extraInitializers);
            __esDecorate(null, null, _categoryId_decorators, { kind: "field", name: "categoryId", static: false, private: false, access: { has: obj => "categoryId" in obj, get: obj => obj.categoryId, set: (obj, value) => { obj.categoryId = value; } }, metadata: _metadata }, _categoryId_initializers, _categoryId_extraInitializers);
            __esDecorate(null, null, _catalogIds_decorators, { kind: "field", name: "catalogIds", static: false, private: false, access: { has: obj => "catalogIds" in obj, get: obj => obj.catalogIds, set: (obj, value) => { obj.catalogIds = value; } }, metadata: _metadata }, _catalogIds_initializers, _catalogIds_extraInitializers);
            __esDecorate(null, null, _galleryIds_decorators, { kind: "field", name: "galleryIds", static: false, private: false, access: { has: obj => "galleryIds" in obj, get: obj => obj.galleryIds, set: (obj, value) => { obj.galleryIds = value; } }, metadata: _metadata }, _galleryIds_initializers, _galleryIds_extraInitializers);
            __esDecorate(null, null, _galleryUrls_decorators, { kind: "field", name: "galleryUrls", static: false, private: false, access: { has: obj => "galleryUrls" in obj, get: obj => obj.galleryUrls, set: (obj, value) => { obj.galleryUrls = value; } }, metadata: _metadata }, _galleryUrls_initializers, _galleryUrls_extraInitializers);
            __esDecorate(null, null, _specsText_decorators, { kind: "field", name: "specsText", static: false, private: false, access: { has: obj => "specsText" in obj, get: obj => obj.specsText, set: (obj, value) => { obj.specsText = value; } }, metadata: _metadata }, _specsText_initializers, _specsText_extraInitializers);
            __esDecorate(null, null, _audience_decorators, { kind: "field", name: "audience", static: false, private: false, access: { has: obj => "audience" in obj, get: obj => obj.audience, set: (obj, value) => { obj.audience = value; } }, metadata: _metadata }, _audience_initializers, _audience_extraInitializers);
            __esDecorate(null, null, _formFactors_decorators, { kind: "field", name: "formFactors", static: false, private: false, access: { has: obj => "formFactors" in obj, get: obj => obj.formFactors, set: (obj, value) => { obj.formFactors = value; } }, metadata: _metadata }, _formFactors_initializers, _formFactors_extraInitializers);
            __esDecorate(null, null, _signalProcessing_decorators, { kind: "field", name: "signalProcessing", static: false, private: false, access: { has: obj => "signalProcessing" in obj, get: obj => obj.signalProcessing, set: (obj, value) => { obj.signalProcessing = value; } }, metadata: _metadata }, _signalProcessing_initializers, _signalProcessing_extraInitializers);
            __esDecorate(null, null, _powerLevel_decorators, { kind: "field", name: "powerLevel", static: false, private: false, access: { has: obj => "powerLevel" in obj, get: obj => obj.powerLevel, set: (obj, value) => { obj.powerLevel = value; } }, metadata: _metadata }, _powerLevel_initializers, _powerLevel_extraInitializers);
            __esDecorate(null, null, _hearingLossLevels_decorators, { kind: "field", name: "hearingLossLevels", static: false, private: false, access: { has: obj => "hearingLossLevels" in obj, get: obj => obj.hearingLossLevels, set: (obj, value) => { obj.hearingLossLevels = value; } }, metadata: _metadata }, _hearingLossLevels_initializers, _hearingLossLevels_extraInitializers);
            __esDecorate(null, null, _smartphoneCompatibility_decorators, { kind: "field", name: "smartphoneCompatibility", static: false, private: false, access: { has: obj => "smartphoneCompatibility" in obj, get: obj => obj.smartphoneCompatibility, set: (obj, value) => { obj.smartphoneCompatibility = value; } }, metadata: _metadata }, _smartphoneCompatibility_initializers, _smartphoneCompatibility_extraInitializers);
            __esDecorate(null, null, _tinnitusSupport_decorators, { kind: "field", name: "tinnitusSupport", static: false, private: false, access: { has: obj => "tinnitusSupport" in obj, get: obj => obj.tinnitusSupport, set: (obj, value) => { obj.tinnitusSupport = value; } }, metadata: _metadata }, _tinnitusSupport_initializers, _tinnitusSupport_extraInitializers);
            __esDecorate(null, null, _paymentOptions_decorators, { kind: "field", name: "paymentOptions", static: false, private: false, access: { has: obj => "paymentOptions" in obj, get: obj => obj.paymentOptions, set: (obj, value) => { obj.paymentOptions = value; } }, metadata: _metadata }, _paymentOptions_initializers, _paymentOptions_extraInitializers);
            __esDecorate(null, null, _availabilityStatus_decorators, { kind: "field", name: "availabilityStatus", static: false, private: false, access: { has: obj => "availabilityStatus" in obj, get: obj => obj.availabilityStatus, set: (obj, value) => { obj.availabilityStatus = value; } }, metadata: _metadata }, _availabilityStatus_initializers, _availabilityStatus_extraInitializers);
            __esDecorate(null, null, _intro_uz_decorators, { kind: "field", name: "intro_uz", static: false, private: false, access: { has: obj => "intro_uz" in obj, get: obj => obj.intro_uz, set: (obj, value) => { obj.intro_uz = value; } }, metadata: _metadata }, _intro_uz_initializers, _intro_uz_extraInitializers);
            __esDecorate(null, null, _intro_ru_decorators, { kind: "field", name: "intro_ru", static: false, private: false, access: { has: obj => "intro_ru" in obj, get: obj => obj.intro_ru, set: (obj, value) => { obj.intro_ru = value; } }, metadata: _metadata }, _intro_ru_initializers, _intro_ru_extraInitializers);
            __esDecorate(null, null, _features_uz_decorators, { kind: "field", name: "features_uz", static: false, private: false, access: { has: obj => "features_uz" in obj, get: obj => obj.features_uz, set: (obj, value) => { obj.features_uz = value; } }, metadata: _metadata }, _features_uz_initializers, _features_uz_extraInitializers);
            __esDecorate(null, null, _features_ru_decorators, { kind: "field", name: "features_ru", static: false, private: false, access: { has: obj => "features_ru" in obj, get: obj => obj.features_ru, set: (obj, value) => { obj.features_ru = value; } }, metadata: _metadata }, _features_ru_initializers, _features_ru_extraInitializers);
            __esDecorate(null, null, _benefits_uz_decorators, { kind: "field", name: "benefits_uz", static: false, private: false, access: { has: obj => "benefits_uz" in obj, get: obj => obj.benefits_uz, set: (obj, value) => { obj.benefits_uz = value; } }, metadata: _metadata }, _benefits_uz_initializers, _benefits_uz_extraInitializers);
            __esDecorate(null, null, _benefits_ru_decorators, { kind: "field", name: "benefits_ru", static: false, private: false, access: { has: obj => "benefits_ru" in obj, get: obj => obj.benefits_ru, set: (obj, value) => { obj.benefits_ru = value; } }, metadata: _metadata }, _benefits_ru_initializers, _benefits_ru_extraInitializers);
            __esDecorate(null, null, _tech_uz_decorators, { kind: "field", name: "tech_uz", static: false, private: false, access: { has: obj => "tech_uz" in obj, get: obj => obj.tech_uz, set: (obj, value) => { obj.tech_uz = value; } }, metadata: _metadata }, _tech_uz_initializers, _tech_uz_extraInitializers);
            __esDecorate(null, null, _tech_ru_decorators, { kind: "field", name: "tech_ru", static: false, private: false, access: { has: obj => "tech_ru" in obj, get: obj => obj.tech_ru, set: (obj, value) => { obj.tech_ru = value; } }, metadata: _metadata }, _tech_ru_initializers, _tech_ru_extraInitializers);
            __esDecorate(null, null, _fittingRange_uz_decorators, { kind: "field", name: "fittingRange_uz", static: false, private: false, access: { has: obj => "fittingRange_uz" in obj, get: obj => obj.fittingRange_uz, set: (obj, value) => { obj.fittingRange_uz = value; } }, metadata: _metadata }, _fittingRange_uz_initializers, _fittingRange_uz_extraInitializers);
            __esDecorate(null, null, _fittingRange_ru_decorators, { kind: "field", name: "fittingRange_ru", static: false, private: false, access: { has: obj => "fittingRange_ru" in obj, get: obj => obj.fittingRange_ru, set: (obj, value) => { obj.fittingRange_ru = value; } }, metadata: _metadata }, _fittingRange_ru_initializers, _fittingRange_ru_extraInitializers);
            __esDecorate(null, null, _regulatoryNote_uz_decorators, { kind: "field", name: "regulatoryNote_uz", static: false, private: false, access: { has: obj => "regulatoryNote_uz" in obj, get: obj => obj.regulatoryNote_uz, set: (obj, value) => { obj.regulatoryNote_uz = value; } }, metadata: _metadata }, _regulatoryNote_uz_initializers, _regulatoryNote_uz_extraInitializers);
            __esDecorate(null, null, _regulatoryNote_ru_decorators, { kind: "field", name: "regulatoryNote_ru", static: false, private: false, access: { has: obj => "regulatoryNote_ru" in obj, get: obj => obj.regulatoryNote_ru, set: (obj, value) => { obj.regulatoryNote_ru = value; } }, metadata: _metadata }, _regulatoryNote_ru_initializers, _regulatoryNote_ru_extraInitializers);
            __esDecorate(null, null, _relatedProductIds_decorators, { kind: "field", name: "relatedProductIds", static: false, private: false, access: { has: obj => "relatedProductIds" in obj, get: obj => obj.relatedProductIds, set: (obj, value) => { obj.relatedProductIds = value; } }, metadata: _metadata }, _relatedProductIds_initializers, _relatedProductIds_extraInitializers);
            __esDecorate(null, null, _usefulArticleSlugs_decorators, { kind: "field", name: "usefulArticleSlugs", static: false, private: false, access: { has: obj => "usefulArticleSlugs" in obj, get: obj => obj.usefulArticleSlugs, set: (obj, value) => { obj.usefulArticleSlugs = value; } }, metadata: _metadata }, _usefulArticleSlugs_initializers, _usefulArticleSlugs_extraInitializers);
            __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
            if (_metadata) Object.defineProperty(this, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        }
        name_uz = __runInitializers(this, _name_uz_initializers, void 0);
        name_ru = (__runInitializers(this, _name_uz_extraInitializers), __runInitializers(this, _name_ru_initializers, void 0));
        slug = (__runInitializers(this, _name_ru_extraInitializers), __runInitializers(this, _slug_initializers, void 0));
        productType = (__runInitializers(this, _slug_extraInitializers), __runInitializers(this, _productType_initializers, void 0));
        description_uz = (__runInitializers(this, _productType_extraInitializers), __runInitializers(this, _description_uz_initializers, void 0));
        description_ru = (__runInitializers(this, _description_uz_extraInitializers), __runInitializers(this, _description_ru_initializers, void 0));
        price = (__runInitializers(this, _description_ru_extraInitializers), __runInitializers(this, _price_initializers, void 0));
        stock = (__runInitializers(this, _price_extraInitializers), __runInitializers(this, _stock_initializers, void 0));
        brandId = (__runInitializers(this, _stock_extraInitializers), __runInitializers(this, _brandId_initializers, void 0));
        categoryId = (__runInitializers(this, _brandId_extraInitializers), __runInitializers(this, _categoryId_initializers, void 0));
        catalogIds = (__runInitializers(this, _categoryId_extraInitializers), __runInitializers(this, _catalogIds_initializers, void 0));
        galleryIds = (__runInitializers(this, _catalogIds_extraInitializers), __runInitializers(this, _galleryIds_initializers, void 0));
        galleryUrls = (__runInitializers(this, _galleryIds_extraInitializers), __runInitializers(this, _galleryUrls_initializers, void 0));
        specsText = (__runInitializers(this, _galleryUrls_extraInitializers), __runInitializers(this, _specsText_initializers, void 0));
        audience = (__runInitializers(this, _specsText_extraInitializers), __runInitializers(this, _audience_initializers, void 0));
        formFactors = (__runInitializers(this, _audience_extraInitializers), __runInitializers(this, _formFactors_initializers, void 0));
        signalProcessing = (__runInitializers(this, _formFactors_extraInitializers), __runInitializers(this, _signalProcessing_initializers, void 0));
        powerLevel = (__runInitializers(this, _signalProcessing_extraInitializers), __runInitializers(this, _powerLevel_initializers, void 0));
        hearingLossLevels = (__runInitializers(this, _powerLevel_extraInitializers), __runInitializers(this, _hearingLossLevels_initializers, void 0));
        smartphoneCompatibility = (__runInitializers(this, _hearingLossLevels_extraInitializers), __runInitializers(this, _smartphoneCompatibility_initializers, void 0));
        tinnitusSupport = (__runInitializers(this, _smartphoneCompatibility_extraInitializers), __runInitializers(this, _tinnitusSupport_initializers, void 0));
        paymentOptions = (__runInitializers(this, _tinnitusSupport_extraInitializers), __runInitializers(this, _paymentOptions_initializers, void 0));
        availabilityStatus = (__runInitializers(this, _paymentOptions_extraInitializers), __runInitializers(this, _availabilityStatus_initializers, void 0));
        intro_uz = (__runInitializers(this, _availabilityStatus_extraInitializers), __runInitializers(this, _intro_uz_initializers, void 0));
        intro_ru = (__runInitializers(this, _intro_uz_extraInitializers), __runInitializers(this, _intro_ru_initializers, void 0));
        features_uz = (__runInitializers(this, _intro_ru_extraInitializers), __runInitializers(this, _features_uz_initializers, void 0));
        features_ru = (__runInitializers(this, _features_uz_extraInitializers), __runInitializers(this, _features_ru_initializers, void 0));
        benefits_uz = (__runInitializers(this, _features_ru_extraInitializers), __runInitializers(this, _benefits_uz_initializers, void 0));
        benefits_ru = (__runInitializers(this, _benefits_uz_extraInitializers), __runInitializers(this, _benefits_ru_initializers, void 0));
        tech_uz = (__runInitializers(this, _benefits_ru_extraInitializers), __runInitializers(this, _tech_uz_initializers, void 0));
        tech_ru = (__runInitializers(this, _tech_uz_extraInitializers), __runInitializers(this, _tech_ru_initializers, void 0));
        fittingRange_uz = (__runInitializers(this, _tech_ru_extraInitializers), __runInitializers(this, _fittingRange_uz_initializers, void 0));
        fittingRange_ru = (__runInitializers(this, _fittingRange_uz_extraInitializers), __runInitializers(this, _fittingRange_ru_initializers, void 0));
        regulatoryNote_uz = (__runInitializers(this, _fittingRange_ru_extraInitializers), __runInitializers(this, _regulatoryNote_uz_initializers, void 0));
        regulatoryNote_ru = (__runInitializers(this, _regulatoryNote_uz_extraInitializers), __runInitializers(this, _regulatoryNote_ru_initializers, void 0));
        relatedProductIds = (__runInitializers(this, _regulatoryNote_ru_extraInitializers), __runInitializers(this, _relatedProductIds_initializers, void 0));
        usefulArticleSlugs = (__runInitializers(this, _relatedProductIds_extraInitializers), __runInitializers(this, _usefulArticleSlugs_initializers, void 0));
        status = (__runInitializers(this, _usefulArticleSlugs_extraInitializers), __runInitializers(this, _status_initializers, void 0));
        constructor() {
            __runInitializers(this, _status_extraInitializers);
        }
    };
})();
exports.CreateProductDto = CreateProductDto;
//# sourceMappingURL=create-product.dto.js.map