import { ProductsService } from './products.service';
import { Response } from 'express';
export declare class ProductsController {
    private readonly productsService;
    constructor(productsService: ProductsService);
    findAll(filters: {
        status?: string;
        brandId?: string;
        categoryId?: string;
        catalogId?: string;
        productType?: string;
        search?: string;
        audience?: string;
        formFactor?: string;
        signalProcessing?: string;
        powerLevel?: string;
        hearingLossLevel?: string;
        smartphoneCompatibility?: string;
        paymentOption?: string;
        availabilityStatus?: string;
        limit?: string;
        offset?: string;
        sort?: 'newest' | 'price_asc' | 'price_desc';
    }): Promise<{
        items: ({
            category: {
                id: string;
                slug: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            } | null;
            brand: {
                name: string;
                id: string;
                slug: string;
                desc_uz: string | null;
                desc_ru: string | null;
                logoId: string | null;
            } | null;
            catalogs: {
                id: string;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                showOnHomepage: boolean;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            categoryId: string | null;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            galleryIds: string[];
            usefulArticleSlugs: string[];
            productType: string | null;
            price: import("@prisma/client/runtime/library").Decimal | null;
            stock: number | null;
            brandId: string | null;
            specsText: string | null;
            galleryUrls: string[];
            audience: string[];
            formFactors: string[];
            signalProcessing: string | null;
            powerLevel: string | null;
            hearingLossLevels: string[];
            smartphoneCompatibility: string[];
            tinnitusSupport: boolean | null;
            paymentOptions: string[];
            availabilityStatus: string | null;
            intro_uz: string | null;
            intro_ru: string | null;
            features_uz: string[];
            features_ru: string[];
            benefits_uz: string[];
            benefits_ru: string[];
            tech_uz: string | null;
            tech_ru: string | null;
            fittingRange_uz: string | null;
            fittingRange_ru: string | null;
            regulatoryNote_uz: string | null;
            regulatoryNote_ru: string | null;
            relatedProductIds: string[];
            thumbnailId: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findBySlug(slug: string): Promise<{
        relatedProducts: ({
            category: {
                id: string;
                slug: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            } | null;
            brand: {
                name: string;
                id: string;
                slug: string;
                desc_uz: string | null;
                desc_ru: string | null;
                logoId: string | null;
            } | null;
            catalogs: {
                id: string;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                showOnHomepage: boolean;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            categoryId: string | null;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            galleryIds: string[];
            usefulArticleSlugs: string[];
            productType: string | null;
            price: import("@prisma/client/runtime/library").Decimal | null;
            stock: number | null;
            brandId: string | null;
            specsText: string | null;
            galleryUrls: string[];
            audience: string[];
            formFactors: string[];
            signalProcessing: string | null;
            powerLevel: string | null;
            hearingLossLevels: string[];
            smartphoneCompatibility: string[];
            tinnitusSupport: boolean | null;
            paymentOptions: string[];
            availabilityStatus: string | null;
            intro_uz: string | null;
            intro_ru: string | null;
            features_uz: string[];
            features_ru: string[];
            benefits_uz: string[];
            benefits_ru: string[];
            tech_uz: string | null;
            tech_ru: string | null;
            fittingRange_uz: string | null;
            fittingRange_ru: string | null;
            regulatoryNote_uz: string | null;
            regulatoryNote_ru: string | null;
            relatedProductIds: string[];
            thumbnailId: string | null;
        })[];
        usefulArticles: {
            id: string;
            title_uz: string;
            title_ru: string;
            slug: string;
            excerpt_uz: string | null;
            excerpt_ru: string | null;
        }[];
        category: {
            id: string;
            slug: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
        brand: {
            name: string;
            id: string;
            slug: string;
            desc_uz: string | null;
            desc_ru: string | null;
            logoId: string | null;
        } | null;
        catalogs: {
            id: string;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            showOnHomepage: boolean;
        }[];
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        categoryId: string | null;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        galleryIds: string[];
        usefulArticleSlugs: string[];
        productType: string | null;
        price: import("@prisma/client/runtime/library").Decimal | null;
        stock: number | null;
        brandId: string | null;
        specsText: string | null;
        galleryUrls: string[];
        audience: string[];
        formFactors: string[];
        signalProcessing: string | null;
        powerLevel: string | null;
        hearingLossLevels: string[];
        smartphoneCompatibility: string[];
        tinnitusSupport: boolean | null;
        paymentOptions: string[];
        availabilityStatus: string | null;
        intro_uz: string | null;
        intro_ru: string | null;
        features_uz: string[];
        features_ru: string[];
        benefits_uz: string[];
        benefits_ru: string[];
        tech_uz: string | null;
        tech_ru: string | null;
        fittingRange_uz: string | null;
        fittingRange_ru: string | null;
        regulatoryNote_uz: string | null;
        regulatoryNote_ru: string | null;
        relatedProductIds: string[];
        thumbnailId: string | null;
    }>;
    findAllAdmin(filters: {
        status?: string;
        brandId?: string;
        categoryId?: string;
        search?: string;
        audience?: string;
        formFactor?: string;
        signalProcessing?: string;
        powerLevel?: string;
        hearingLossLevel?: string;
        smartphoneCompatibility?: string;
        paymentOption?: string;
        availabilityStatus?: string;
    }): Promise<{
        items: ({
            category: {
                id: string;
                slug: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                parentId: string | null;
            } | null;
            brand: {
                name: string;
                id: string;
                slug: string;
                desc_uz: string | null;
                desc_ru: string | null;
                logoId: string | null;
            } | null;
            catalogs: {
                id: string;
                slug: string;
                status: string;
                name_uz: string;
                name_ru: string;
                description_uz: string | null;
                description_ru: string | null;
                imageId: string | null;
                order: number;
                icon: string | null;
                showOnHomepage: boolean;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            slug: string;
            categoryId: string | null;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            galleryIds: string[];
            usefulArticleSlugs: string[];
            productType: string | null;
            price: import("@prisma/client/runtime/library").Decimal | null;
            stock: number | null;
            brandId: string | null;
            specsText: string | null;
            galleryUrls: string[];
            audience: string[];
            formFactors: string[];
            signalProcessing: string | null;
            powerLevel: string | null;
            hearingLossLevels: string[];
            smartphoneCompatibility: string[];
            tinnitusSupport: boolean | null;
            paymentOptions: string[];
            availabilityStatus: string | null;
            intro_uz: string | null;
            intro_ru: string | null;
            features_uz: string[];
            features_ru: string[];
            benefits_uz: string[];
            benefits_ru: string[];
            tech_uz: string | null;
            tech_ru: string | null;
            fittingRange_uz: string | null;
            fittingRange_ru: string | null;
            regulatoryNote_uz: string | null;
            regulatoryNote_ru: string | null;
            relatedProductIds: string[];
            thumbnailId: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findOne(id: string): Promise<{
        category: {
            id: string;
            slug: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
        brand: {
            name: string;
            id: string;
            slug: string;
            desc_uz: string | null;
            desc_ru: string | null;
            logoId: string | null;
        } | null;
        catalogs: {
            id: string;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            showOnHomepage: boolean;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        categoryId: string | null;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        galleryIds: string[];
        usefulArticleSlugs: string[];
        productType: string | null;
        price: import("@prisma/client/runtime/library").Decimal | null;
        stock: number | null;
        brandId: string | null;
        specsText: string | null;
        galleryUrls: string[];
        audience: string[];
        formFactors: string[];
        signalProcessing: string | null;
        powerLevel: string | null;
        hearingLossLevels: string[];
        smartphoneCompatibility: string[];
        tinnitusSupport: boolean | null;
        paymentOptions: string[];
        availabilityStatus: string | null;
        intro_uz: string | null;
        intro_ru: string | null;
        features_uz: string[];
        features_ru: string[];
        benefits_uz: string[];
        benefits_ru: string[];
        tech_uz: string | null;
        tech_ru: string | null;
        fittingRange_uz: string | null;
        fittingRange_ru: string | null;
        regulatoryNote_uz: string | null;
        regulatoryNote_ru: string | null;
        relatedProductIds: string[];
        thumbnailId: string | null;
    }>;
    create(createDto: unknown): Promise<{
        category: {
            id: string;
            slug: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
        brand: {
            name: string;
            id: string;
            slug: string;
            desc_uz: string | null;
            desc_ru: string | null;
            logoId: string | null;
        } | null;
        catalogs: {
            id: string;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            showOnHomepage: boolean;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        categoryId: string | null;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        galleryIds: string[];
        usefulArticleSlugs: string[];
        productType: string | null;
        price: import("@prisma/client/runtime/library").Decimal | null;
        stock: number | null;
        brandId: string | null;
        specsText: string | null;
        galleryUrls: string[];
        audience: string[];
        formFactors: string[];
        signalProcessing: string | null;
        powerLevel: string | null;
        hearingLossLevels: string[];
        smartphoneCompatibility: string[];
        tinnitusSupport: boolean | null;
        paymentOptions: string[];
        availabilityStatus: string | null;
        intro_uz: string | null;
        intro_ru: string | null;
        features_uz: string[];
        features_ru: string[];
        benefits_uz: string[];
        benefits_ru: string[];
        tech_uz: string | null;
        tech_ru: string | null;
        fittingRange_uz: string | null;
        fittingRange_ru: string | null;
        regulatoryNote_uz: string | null;
        regulatoryNote_ru: string | null;
        relatedProductIds: string[];
        thumbnailId: string | null;
    }>;
    update(id: string, updateDto: unknown): Promise<{
        category: {
            id: string;
            slug: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            parentId: string | null;
        } | null;
        brand: {
            name: string;
            id: string;
            slug: string;
            desc_uz: string | null;
            desc_ru: string | null;
            logoId: string | null;
        } | null;
        catalogs: {
            id: string;
            slug: string;
            status: string;
            name_uz: string;
            name_ru: string;
            description_uz: string | null;
            description_ru: string | null;
            imageId: string | null;
            order: number;
            icon: string | null;
            showOnHomepage: boolean;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        categoryId: string | null;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        galleryIds: string[];
        usefulArticleSlugs: string[];
        productType: string | null;
        price: import("@prisma/client/runtime/library").Decimal | null;
        stock: number | null;
        brandId: string | null;
        specsText: string | null;
        galleryUrls: string[];
        audience: string[];
        formFactors: string[];
        signalProcessing: string | null;
        powerLevel: string | null;
        hearingLossLevels: string[];
        smartphoneCompatibility: string[];
        tinnitusSupport: boolean | null;
        paymentOptions: string[];
        availabilityStatus: string | null;
        intro_uz: string | null;
        intro_ru: string | null;
        features_uz: string[];
        features_ru: string[];
        benefits_uz: string[];
        benefits_ru: string[];
        tech_uz: string | null;
        tech_ru: string | null;
        fittingRange_uz: string | null;
        fittingRange_ru: string | null;
        regulatoryNote_uz: string | null;
        regulatoryNote_ru: string | null;
        relatedProductIds: string[];
        thumbnailId: string | null;
    }>;
    remove(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        slug: string;
        categoryId: string | null;
        status: string;
        name_uz: string;
        name_ru: string;
        description_uz: string | null;
        description_ru: string | null;
        galleryIds: string[];
        usefulArticleSlugs: string[];
        productType: string | null;
        price: import("@prisma/client/runtime/library").Decimal | null;
        stock: number | null;
        brandId: string | null;
        specsText: string | null;
        galleryUrls: string[];
        audience: string[];
        formFactors: string[];
        signalProcessing: string | null;
        powerLevel: string | null;
        hearingLossLevels: string[];
        smartphoneCompatibility: string[];
        tinnitusSupport: boolean | null;
        paymentOptions: string[];
        availabilityStatus: string | null;
        intro_uz: string | null;
        intro_ru: string | null;
        features_uz: string[];
        features_ru: string[];
        benefits_uz: string[];
        benefits_ru: string[];
        tech_uz: string | null;
        tech_ru: string | null;
        fittingRange_uz: string | null;
        fittingRange_ru: string | null;
        regulatoryNote_uz: string | null;
        regulatoryNote_ru: string | null;
        relatedProductIds: string[];
        thumbnailId: string | null;
    }>;
    importExcel(file: Express.Multer.File): Promise<{
        success: number;
        failed: number;
        errors: Array<{
            row: number;
            error: string;
        }>;
    }>;
    downloadExcelTemplate(res: Response): Promise<void>;
}
//# sourceMappingURL=products.controller.d.ts.map